import javax.swing.JOptionPane;

@SuppressWarnings("ALL")
public class ExceptionExc {

    public static void main(String[] args) {
        // TODO autogenerated method stub
        String message = "";
        String stringSpeed = JOptionPane.showInputDialog("What's your speed?");
        try {
            double speed = Double.parseDouble(stringSpeed);
            if (speed <= 90)
                message = "Alright.";
            else
                message = "Ticket.";
        } catch (NumberFormatException e) {
            e.printStackTrace();
            message = "Invalid speed.";
        } finally {
            JOptionPane.showMessageDialog(null, message);
        }


    }
}
